### ISSUE TITLE
block placer will place blocks across dimensions 

### ISSUE THREAD

**Issue by Sunekaer** [stfwi/engineers-decor#225] opened 2022-11-10 11:39 UTC
Block placer can place across dimensions with same dimensionsType
This is an issue we have in FTB StoneBlock 3 because each player have their own dimension, these dims has different ID's but the same type.

**Comment by stfwi** [comment] 2022-11-11 21:23
Hi sunekaer, oky ty for the hint. I'll try to take a look at this in the next few days. Cheers,-

**Comment by stfwi** [comment] 2022-11-12 10:58
Hi again, I added a line explicitly setting the `FakePlayer`s level before it is used to try player-like placement; pretty sure this must have been the issue. A problem is that I cannot explicitly test the fix in the StoneBlock setup this week, so I'll speculatively push the fix to curse/modrinth.

In case you update the pack faster, could you give me quick feedback if the problem is fixed in your setup? Cheers,-

**Closed as completed** 2022-11-26 12:37 UTC
Labels: anomaly, approval-pending, mc1.18, mc1.19
