### ISSUE TITLE
gui crash

### ISSUE THREAD

**Issue by Warbringer12** [stfwi/engineers-decor#119] opened 2020-08-22 04:15 UTC
[crash-2020-08-21_21.11.05-client.txt](https://github.com/stfwi/engineers-decor/files/5111903/crash-2020-08-21_21.11.05-client.txt)
version 1.16.2-1.1.2-b2
forge version 1.16.2 33.0.20

**Comment by stfwi** [comment] 2020-08-23 15:22
Hi, aye, it's already fixed. There was a cleanup in forge 33.0.20 that had to be adapted to. Unfortunately I just pushed the b2 to Curse before I saw the new Forge version ;/. Cheers, -

**Comment by stfwi** [comment] 2020-08-23 20:16
engineersdecor-1.16.2-1.1.2-b3 is pushed on Curse, as the problem was reproducible and known across mods I'll close this issue directly. Thanks again for filing it! Cheers, -

**Closed as completed by stfwi** 2020-08-23 20:16 UTC
Labels: anomaly, scheduled, fixed, mc1.16
