### ISSUE TITLE
[Crash; 1.12.2-1.0.4-b6] Startup crash without IE

### ISSUE THREAD

**Issue by rai-en** [stfwi/engineers-decor#21] opened 2019-04-28 21:49 UTC
Hi again. With the latest release I'll get a startup crash if not also running IE. I believe this should just be due to the new fluid valves not having fallback recipes. 

[crash-2019-04-28_16.43.51-client.txt](https://github.com/stfwi/engineers-decor/files/3125520/crash-2019-04-28_16.43.51-client.txt)

**Comment by stfwi** [comment] 2019-04-29 03:57
Hi, I noticed yesterday after pushing the beta - I forgot to make a recipe conditional, so now it should complain because of a "JSON exception" that ie::material or ie::connector is missing. It's already fixed, just need to push the binary ;)

**Comment by stfwi** [comment] 2019-04-29 17:20
Alright, the new binary is available. I've already tested on my machine, could you double check and confirm that the issue is also solved for you?

**Comment by rai-en** [comment] 2019-04-30 21:48
Fixed on my end as well :)

**Comment by stfwi** [comment] 2019-04-30 23:28
Perfect, then I close this. Thanks for the feedback and reporting!

**Closed as completed by stfwi** 2019-04-30 23:28 UTC
