### ISSUE TITLE
Small electrical furnace and hopper cause crash.

### ISSUE THREAD

**Issue by sarpaslan** [stfwi/engineers-decor#25] opened 2019-05-21 04:19 UTC
I don't exactly know what the real reason behind this bug but maybe you can fix this if this is up to you.

This bug is nearly destroyed my save file. You can never load your world without uninstalling the mod. 

How to reproduce;
[https://youtu.be/B4XW7tyMaX8](https://youtu.be/B4XW7tyMaX8)

[crashreport.txt](https://github.com/stfwi/engineers-decor/files/3200768/crashreport.txt)

minecraft            | 1.12.2       | minecraft.jar         
 FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2811.jar    
engineersdecor       | 1.0.5        | engineersdecor-1.12.2-1.0.5.jar 
immersiveengineering | 0.12-89      | ImmersiveEngineering-0.12-89.jar

**Comment by stfwi** [comment] 2019-05-21 17:51
Hi, many thanks for that level of detail! Really cool. I had this issue last Sunday evening with another block of my mod and could resolve it, unfortunately I could not push it yet. I''ll make a "hot fix release" (hopefully tonight).

**For the record, if someone also gets this exception about "getStackInSlot() is abstract": Check if you implement IItemHandler and IInventory (or ISidedInventory). They both override this method, but due to FML remapping one of them will be remapped to the Minecraft internal symbol, "unlinking from the interface implementation".** It's a tricky one that you don't get while developing and might not get on your testing setup. Solution: Use a separated instance for IItemHandler and do not implement it in the TE class.

**Comment by stfwi** [comment] 2019-05-21 19:01
Ok I pushed the binary (v1.0.6-mc1.12.2) to Curse, if you find the time could you double check and confirm that the issue is fixed on your machine? Cheers and thx!

**Comment by sarpaslan** [comment] 2019-05-22 09:11
Yes, I think it's resolved! 
(Also I tried to get a crash in many ways but I couldn't. )

**Comment by stfwi** [comment] 2019-05-22 15:13
Perfect, thanks for that. I also reproduced the error and then updated to check if "broken games" can continue as normal after the update (also works). 
So let's consider the issue resolved. Cheers -

**Closed as completed by stfwi** 2019-05-22 15:13 UTC
Labels: anomaly
