### ISSUE TITLE
Server Crashing/Client Hanging

### ISSUE THREAD

**Issue by Siriuo** [stfwi/engineers-decor#69] opened 2019-12-07 19:49 UTC
Server will crash with a server hang message. With the same world loaded on client side, the client just hangs indefinitely. As soon as the mod is removed everything works normally.

See crash log at the link below.

https://pastebin.com/LcyLCb7K

**Comment by stfwi** [comment] 2019-12-08 07:36
Hi, probably block::onLoad does get invoked when I don't expect it, should be fixable.

**Comment by stfwi** [comment] 2019-12-08 21:17
Ok, engineersdecor-1.14.4-1.0.17-b1 is approved on curse, could you quickly check if the problem is resolved for you? I could not reproduce it but replaced a method according to your log file, so it should be fixed now.

**Comment by Siriuo** [comment] 2019-12-09 16:11
Seems to have resolved the issue. Will add the mod back to my server and keep an eye.

**Comment by stfwi** [comment] 2019-12-09 18:10
Ok, I close the issue then, if anything seems odd we'll simply reopen it.

**Closed as completed by stfwi** 2019-12-09 18:10 UTC
Labels: anomaly, mc1.14, approval-pending
