### ISSUE TITLE
[1.14.4] block collisions not dissapearing in creative mode

### ISSUE THREAD

**Issue by StrongMint** [stfwi/engineers-decor#48] opened 2019-08-19 17:52 UTC
When breaking items from the world map in creative mode the collisions do not dissapears and react buggy. no crashes though. havent tested all the blocks and items.
it works normal in survival mode.

removed all mods except Engineers-decor. still same issue.

using forge 28.0.45
also tested with 28.0.49 (latest)

**Comment by stfwi** [comment] 2019-08-19 19:43
Hi, thanks for the hint. Quickly looked up the changes in the code and think I already found where I messed up ;). Scheduled for v1.0.11-b2.

**Comment by stfwi** [comment] 2019-08-26 07:31
Ok, b2 built is out. Could you double check and confirm that the issue is resolved for your setup?

**Comment by StrongMint** [comment] 2019-08-26 15:58
issue is resolved now.

Thank you!

**Comment by stfwi** [comment] 2019-08-26 22:17
Perfect, thanks for checking. I close the issue then. Cheers -

**Closed as completed by stfwi** 2019-08-26 22:17 UTC
Labels: anomaly, mc1.14, scheduled
