### ISSUE TITLE
Factory dropper crashes client

### ISSUE THREAD

**Issue by CalvinBard** [stfwi/engineers-decor#114] opened 2020-08-03 12:17 UTC
This is in the 1.16.1 version playing the valhelsia 3 pack,

error log:
[14:14:20] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:120]: ---- Minecraft Crash Report ----// You should try our sister game, Minceraft!Time: 8/3/20 2:14 PMDescription: Rendering screenjava.lang.NoSuchMethodError: net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238654_b_(Lcom/mojang/blaze3d/matrix/MatrixStack;Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V
	at wile.engineersdecor.libmc.detail.TooltipDisplay.lambda$render$0(TooltipDisplay.java:92) ~[?:1.1.1-b4] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_242] {}
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_242] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_242] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242] {}
	at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:526) ~[?:1.8.0_242] {}
	at wile.engineersdecor.libmc.detail.TooltipDisplay.render(TooltipDisplay.java:87) ~[?:1.1.1-b4] {re:classloading,pl:runtimedistcleaner:A}
	at wile.engineersdecor.blocks.EdDropper$DropperGui.func_230430_a_(EdDropper.java:879) ~[?:1.1.1-b4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.75.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

**Comment by stfwi** [comment] 2020-08-03 17:49
Hi, there were changes in a Forge mapping for a UI tooltip method that affects my mod. I have fixed that in mod version v1.1.1-b5, where the change was as of Forge 32.0.75. Which version of the mod/forge is used in your Pack version? Cheers, -

**Comment by stfwi** [comment] 2020-08-03 17:49
Related issue: https://github.com/stfwi/engineers-decor/issues/112

**Comment by stfwi** [comment] 2020-08-03 19:02
Ok, I simply made a hotfix on the mod side and disable the tooltip rendering when there is a mapping issue. Should help to prevent mod downgrading issue in Valhesia.

**Comment by stfwi** [comment] 2020-08-04 13:01
Ok, the Valhesia devs update the mod for the next version. Could you, when downloaded, quickly double check if the issue is gone on your machine and close the issue if so? Cheers, -

**Closed as completed** 2020-08-09 09:16 UTC
Labels: anomaly, approval-pending, compatibility, mc1.16
