### ISSUE TITLE
Dupe bug with Small electrical furnace

### ISSUE THREAD

**Issue by Anto-fire** [stfwi/engineers-decor#174] opened 2021-04-18 17:33 UTC
Using the Storage Drawers mod and the auto pulling feature, the item are pulled infinitely from the drawer without removing it.

**Comment by Anto-fire** [comment] 2021-04-18 17:34
https://youtu.be/fCkTlkBGhQk

**Comment by Anto-fire** [comment] 2021-04-18 17:34
I don't really know how to put a label but I think it's a compatibility issue.

**Comment by IchigoGames** [comment] 2021-04-18 19:13
sorry about this i dont think he knows he needs to give version info

Minecraft 1.16.5
Forge 36.1.4
engineersdecor-1.16.4-1.1.11
StorageDrawers-1.16.3-8.2.2

Happens in modpack Final Frontier 2 6.2

**Comment by stfwi** [comment] 2021-04-18 20:56
Hi guys, thanks for the details and the video, I gonna dig into this in the next days, hopefully can get out a fix for next weekend ("in-week" is busy time ;) ).

**Comment by IchigoGames** [comment] 2021-04-18 21:11
its fine for now i'll just disable the furnace with crafttweaker

**Comment by stfwi** [comment] 2021-04-19 16:43
Oky, had a quick look today already and found it in a minute ;) - Fix version is pushed to Curse and should be approved today then. Could you also take a quick look if possible and close if the problem is resolved in your pack? Cheers!

**Comment by IchigoGames** [comment] 2021-04-19 19:13
Its fixed now

**Closed as completed** 2021-04-19 19:15 UTC
Labels: anomaly, approval-pending, compatibility, mc1.16
