### ISSUE TITLE
Dark shingle blocks/slabs create light

### ISSUE THREAD

**Issue by Murph2** [stfwi/engineers-decor#159] opened 2021-02-08 19:10 UTC
very simple to recreate, place down the block/slab variant of dark shingles and they produce light.
![image](https://user-images.githubusercontent.com/51838690/107269071-0aa04600-6a17-11eb-816e-14613b7090e7.png)
before ^
after v
![image](https://user-images.githubusercontent.com/51838690/107269118-1db31600-6a17-11eb-8766-9e500a04110b.png)
left- shingle slab
middle- shingle block
right- normal shingles

It may be a bug with optifine, im using the latest 1.16.5 stable version. but why the block would do this is beyond me, as no other slabs do this, only this block. In this picture they are not exposed to any light and have skylight blocked off by blocks, they give off enough light to be noticable during the day making a building with them look terrible especially at night, because half of the roof becomes brightly lit for no apparant reason

**Comment by stfwi** [comment] 2021-02-08 19:54
Hi, yes, it's not only optifine, there is a shadow rendering issue that is not resolved yet, the adding light level 1 to the block is a temporary workaround.
Duplicate of issue #153.

**Comment by stfwi** [comment] 2021-02-12 21:51
Alright, checkout the engineersdecor-1.16.4-1.1.8-b1, the shading not yet exactly what I had in mind, but the light emission could be removed. Cheers, -

**Closed as completed by stfwi** 2021-02-12 21:51 UTC
Labels: anomaly, duplicate, rendering, mc1.16
