### ISSUE TITLE
Crash by "Small Block Breaker"

### ISSUE THREAD

**Issue by liopard** [stfwi/engineers-decor#187] opened 2021-09-22 06:43 UTC
I try break "Moon Rock"(galacticraftcore:basic_block_moon:4) by "Small Block Breaker"
[crash.txt](https://github.com/stfwi/engineers-decor/files/7208244/crash.txt)

**Comment by stfwi** [comment] 2021-09-22 16:02
Hi, I took a quick peek into the code and think I know what this is. Cheers,-

**Comment by stfwi** [comment] 2021-09-22 16:34
Yepp, wrong position specified for that ;). The maintenance release `v1.12.2-1.1.3` is pushed on Curse and should be available in a few hours. Can you double check and close the issue if the problem is gone in your setup? Cheers,-

**Closed as completed** 2021-09-23 06:28 UTC
Labels: anomaly, mc1.12, approval-pending

**Comment by liopard** [comment] 2021-09-23 06:31
fixed
