### ISSUE TITLE
Pass Through Furnace Resetting Speed Every Time Game is Launched

### ISSUE THREAD

**Issue by therobotmenace** [stfwi/engineers-decor#97] opened 2020-05-22 17:15 UTC
First off - love the mod! It feels like a very natural addition into Immersive Engineering and lends itself very nicely to automating production lines. 

The issue I'm running into is:
Every time I launch the game the Electrical Pass Through furnace resets itself to one speed step lower than what it was previously at, stopping at speed 1. I can still set the speed back to whatever I want it at, but having to go into my production line and set all of the furnaces back to their max speed every launch is annoying.

**Comment by stfwi** [comment] 2020-05-22 23:18
Hi, thanks for reaching out and reporting. I have already an idea what this could be. Just to quickly ensure, you are running the latest ED version on 1.12.2, not 1.14.4? Cheers -

**Comment by stfwi** [comment] 2020-05-23 08:39
Oh, just took a glimpse, that's a sanitizing bug (sanitizing without sanity), not severe but affects all MC versions of the mod. It's fixed now and scheduled for the next beta iteration.

**Comment by stfwi** [comment] 2020-05-30 07:07
v1.1.0-b1 is up on Curse. Could you double check if the problem is gone for your setup and close the issue if so? Cheers -

**Closed as completed** 2020-06-11 11:35 UTC
Labels: anomaly, mc1.14, mc1.12, approval-pending, mc1.15
