### ISSUE TITLE
[Bug] Factory Block Placer vs Falling Block Entities

### ISSUE THREAD

**Issue by DrakoAlcarus** [stfwi/engineers-decor#98] opened 2020-06-11 19:47 UTC
When placing Vanilla Concrete Powder into the FBP, it places additional blocks inside the falling entities. This causes the Concrete Powder or any falling block to drop on the ground while the first falling block becomes solid.

You can recreate this with this design I made to auto-process Concrete into the wonderful hard block we know and love:
![image](https://user-images.githubusercontent.com/12781728/84431143-a86d1800-abdf-11ea-882b-653dff3bb726.png)

Now that I look at it, this design can be very much streamlined to prevent this, however, it does seem to be a valid bug. This can be fixed if you add falling entities to a list of entities that interrupt the machine.

**Comment by stfwi** [comment] 2020-06-12 16:26
Hey, good point, I did not have falling blocks on screen. Let me schedule this for 1.1.0-b3 (I built b2 already and was testing). Maybe extending the placement blocking to any entities that can be collided include falling block, if so we'll go with that. Fake lights etc have to be ignored however.

**Comment by DrakoAlcarus** [comment] 2020-06-12 16:30
Fake lights and arrows, of course

**Comment by stfwi** [comment] 2020-06-14 18:54
Quickly hacked the collidable-entity check, seems to pass all the quick tests done, also ignoring arrows. Gonna put it in the next release.

**Comment by DrakoAlcarus** [comment] 2020-06-14 18:56
Excellent! Very attentive.

**Comment by stfwi** [comment] 2020-06-21 18:38
Alright, `engineersdecor-1.15.2-1.1.0-b3` is uploaded. Could you check and close the issue if the problem is resolved for you? Cheers, -

**Closed as completed** 2020-06-28 16:15 UTC
Labels: anomaly, mc1.14, mc1.12, approval-pending, mc1.15
