### ISSUE TITLE
Factory Hopper dupe glitch

### ISSUE THREAD

**Issue by FatheredPuma81** [stfwi/engineers-decor#146] opened 2020-12-14 00:58 UTC
**How:** Drop any item directly in the middle of 4 2x2 Factory Hoppers. Repeat until duplicates. Hypothetically should duplicate more with 8x8 and Factory Hopper radius at maximum. May also work if item isn't directly in middle.
**MCVersion:** 1.16.4
**ForgeVersion:** 35.1.13
**ModVersion:** 1.16.4-1.1.4
**Possible Mod Conflict?:** ItemPhysic Full
**Server?** Yes, **Client?** Haven't tested

**Comment by stfwi** [comment] 2020-12-14 20:01
Hi, ty for the details. I made a quick test setup on my local server and let it run for an hour - without a single collection dupe. Versions were `forge35.1.13`, `engineers-decor-1.16.4-1.1.4`, `creativecore2.0.0`, `itemphysic1.6.0` (also other mods, IE, G&S, etc).
So this could be a cross-mod issue, I'll dive into the code at the weekend to check for race conditions.
If possible, could you update all mods and try to reproduce on your machine? 
Cheers, - 
![2020-12-14-repr-fh-dupe](https://user-images.githubusercontent.com/28822525/102129103-23dda980-3e4f-11eb-9985-c25159ddef89.png)

**Comment by FatheredPuma81** [comment] 2020-12-14 20:48
Sorry I don't think my original post was clear enough. Not sure what the screenshot you posted shows as I haven't even gotten around to figuring out Immersive Engineering in my world yet and used them for picking up mob drops. Anyways I tested it in just a normal superflat, singleplayer, only IE and Engineers Decor, and was able to recreate it. 
Make a video of me doing it although the results were no where near as extreme as when I found it after I duped 1 spawner into 13 within around 5 minutes although my hopper settings were set to 4 radius and 32 item transfer which may change the results.
https://streamable.com/zmykvn

**Comment by stfwi** [comment] 2020-12-15 19:39
Oky perfect that, thx for the vid. Gonna schedule a fix for the next beta/release.

**Comment by stfwi** [comment] 2020-12-16 20:54
Yeh, got it, needed to check if removed items are actually already removed when collecting ;)

**Comment by stfwi** [comment] 2020-12-19 09:16
Alright, engineersdecor-1.16.4-1.1.5 is up on Curse, if you could also make a final double check if the bug is also gone for your setup and close the issue if so wood be cool, cheers!

**Comment by FatheredPuma81** [comment] 2020-12-19 11:02
> Alright, engineersdecor-1.16.4-1.1.5 is up on Curse, if you could also make a final double check if the bug is also gone for your setup and close the issue if so wood be cool, cheers!

Yep just checked by dropping 3 stacks in and it looks like it's fixed :D.

**Closed as completed** 2020-12-19 11:03 UTC
Labels: anomaly, scheduled, approval-pending, mc1.16
