### ISSUE TITLE
[1.16.1] Rain and snow are not visible through the windows

### ISSUE THREAD

**Issue by Patronelli** [stfwi/engineers-decor#110] opened 2020-07-27 18:48 UTC
Minenecraft 1.16.1
engineersdecor-1.16.1-1.1.1-b4
forge-1.16.1-32.0.75

There's that problem even using only Engineer's Decor mod.

**Comment by stfwi** [comment] 2020-07-28 17:04
Ok, cheers for transferring the issue here on the hub.

**Comment by stfwi** [comment] 2020-07-29 20:23
Quickly peeked, currently the issue is not solvable without a MC fix e.g. in Forge (the model composition changed here, which likely requires an additional rendering type). That may need time, so I'll defer the issue for now.

**Comment by stfwi** [comment] 2020-10-02 14:09
Oky doke, I did dig into that - and it's actually a vanilla thing and not a bug (https://bugs.mojang.com/browse/MC-201278). What I forgot to do initially is to check how vanilla Stained Glass Panes render. They render the same as the mod windows.

To see rain/snow/particles behind translucent blocks ***we have to set the graphics to "Fabulous!" instead of "Fancy" ;-)***.
(So I'll close the issue).

**Closed as completed by stfwi** 2020-10-02 14:09 UTC
Labels: rendering, config, mc1.16, works-as-expected
